### ISSUE TITLE
Include a `rawgit` link in Specification README files

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#1]

**Comment by mglanville** [comment]
We decided it was more useful to link to the AMWA project page for the Specification. Linking directly to a rawgit URL would involve knowing which branch/tag/commit to link to, and that would probably change when a Specification in elevated to the next phase of development.

**Comment by bgilmer77** [comment]
We want anyone looking for an approved specification to start at the Amwa website. It is the authoritative source of what has been voted on and approved. We will use indirection from the website to allow us to point to a specific tagged release as an approved specification.
