### ISSUE TITLE
Embed TTML Subtitles into MXF files in future AS-11 X* Specs?

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#100]
I assume that using RP 2057 would be the best approach. Need to give consideration to how big these subtitles XML files would be though and therefore which embedding mechanism is used.

We assume no other resources need to be embedded along with the Timed Text (such as fonts, images, etc)

Our working assumption is that there will be a single XML document (per caption "stream") that is mapped into the file as a single "blob" of XML. We see no requirement to spread it throughout the file.

ST 429-5 describes a Timed Text Track File -- it describes the mapping of an XML document and associated resources into an MXF file. This is probably not appropriate here because:

* The MXF file would only contain these Timed Text related assets and no A/V
* The XML is Clip Wrapped in a Data Item in the Generic Container

It does provide a TimeTextDescriptor. It's good to note that it contains the following properties which are all covered by RP 2057:

* ResourceID
* UCSEncoding
* NamespaceUUI

Are these sufficient for describing the TTML? -- if the TTML itself contains all other essential metadata then probably, yes. Would there be a need for a "language" metadata property, for example?

Note that EBU R 133 (Subtitles in an MXF-based TV Production Environment) references SMPTE ST 410 (Generic Stream Partition).

**Comment by thomasheritage** [comment]
@matthewmarks-bbc good to update this issue with the approach actually taken, and close it

**Comment by matthewmarks-bbc** [comment]
[AS-11 X5](https://amwa-tv.github.io/AS-11_X5/AMWA_AS_11_X5.html) and [X6](https://amwa-tv.github.io/AS-11_X6/AMWA_AS_11_X6.html) support [TTML subtitles](https://amwa-tv.github.io/AS-11_X6/AMWA_AS_11_X6.html#2c45d4bdbb4231537a614a192072ed54) as IMSC 1.1, but following as far as possible the Generic Stream Partition practice adopted by IMF, from which many of these files are likely to be sourced. Resources can also be included if necessary.

In addition, X6 (HD) supports [teletext subtitles](https://amwa-tv.github.io/AS-11_X6/AMWA_AS_11_X6.html#95323aeda9e1c28fcf3b916fd3aae340) for compatibility with legacy systems.
