### ISSUE TITLE
Add AS-11 X5 and X6 (DPP UHD and HD Commercials and Promotions)

### ISSUE THREAD

**Issue by matthewmarks-bbc** [AMWA-TV/AS-11_Overview#104]
- [X] Formal project proposal
- [X] AMWA board approval for the new Spec
- [X] Assign Spec Identifers (AS-11 X5 and AS-11 X6)
- [X] Agree listing details for the new Specification (title, description, etc)
- [X] Update the AMWA website to list the basic details of the new Specs
- [x] Create Private GitHub repos for the Specs
- [x] Configure new GitHub repos
- [x] Agree outline design for the new Specs
- [x] Create Blocks for new Specs in dev system
- [x] Create full details for the new Specs (title, purpose, example XMLs, etc) in dev system
- [x] Populate GitHub repo for the Specs
- [x] Provide IPR declaration form for the contribution to GitHub
- [x] Make the GitHub projects public
- [x] Update the AMWA website to list the full details of the new Specs
~- [ ] Update the Tech Overview PowerPoint on the AMWA website~

(Based on [issue 33](https://github.com/AMWA-TV/AS-11_Overview/issues/33))

**Comment by matthewmarks-bbc** [comment]
@bgilmer77 Can you create empty, private repos for AS-11_X5 and AS-11_X6 please.

**Comment by peterbrightwell** [comment]
@matthewmarks-bbc  @bgilmer77: Note that we are currently at the max number (10) for private repos on AMWA’s current GitHub plan.  I should be able to free up one slot used for NMOS in the near future, but not immediately.  Once the work I’m doing on spec process is public I can free up another two.  But most of the private repos are used for AS-11 work, so if you’re going to need >10 private repos we will need to change plan (Brad – see my email about this on Oct 30).

P

**Comment by bgilmer77** [comment]
I will change the plan and create the repositories…

**Comment by bgilmer77** [comment]
Done.  The rules-admin Team now has admin rights to these new private repos.

**Comment by thomasheritage** [comment]
IPR declaration forms for X5 and X6 have now been submitted by BBC R&D to AMWA.
