### ISSUE TITLE
AS-11 X9: register symbol BLOCKS_FF_X9

### ISSUE THREAD

**Issue by matthewmarks-bbc** [AMWA-TV/AS-11_Overview#110]
Currently at https://www.amwa.tv/rawgit/AMWA-TV/AS-11_X9/master/specification_data_files/vm-1274-user.virt.ch.bbc.co.uk_c064c30/block/SpecID_LX9/artefacts/Labels.xml

**Comment by thomasheritage** [comment]
I've made a Submission of this new Labels Register entry to SMPTE 30MR10 for processing.

**Comment by thomasheritage** [comment]
This Submission has now been "accepted" and so is complete.

This means that this Label now appears in the public "draft" SMPTE Metadata Registers at https://registry.smpte-ra.org/view/draft/labels_view.html

It will now automatically get included in the next official formal "publication" snapshot of the Registers (made every 6-12 months).
