### ISSUE TITLE
Conform to new Specification levels

### ISSUE THREAD

**Issue by matthewmarks-bbc** [AMWA-TV/AS-11_Overview#119]
As per [updated BCP-001](https://amwa.tv/projects/BCP-001.1_2018-06-26.pdf) and discussed with AMWA.

In HTML renderings,

- `[Work In Progress]` is unchanged
- `[Proposed Specification]` becomes `[Specification]`
- `[Specification]` becomes `[Specification (Stable)]`
<br><br>
- [x] Modify rules generator to use new names
- [x] Check for knock-ons in the tutorials and update accordingly
- [x] Update [Introduction to the new Rules-based approach](https://amwa.tv/downloads/specifications/New_Approach_to_Specification_Design_and_Publication.pdf)
- [ ] AMWA replaces document on website
- [x] Obtain approval from AMWA board to apply Stable tag to UK_DPP_SD and UK_DPP_HD (as currently at Specification level)
- [x] Change UK_DPP_SD, UK_DPP_HD, X2, X7, (X8?), X9 recipes' "specification_status" element to use new names
- [x] Edit affected existing "Proposed Specification" releases in Specification repos to point out that the name has changed
- [x] Regenerate and push affected Specifications
- [x] Inform the AMWA about updates to affected web pages
- [ ] AMWA updates web pages

**Comment by thomasheritage** [comment]
I think the only impact on the rules-processor is the colour coding it provides -- see https://github.com/AMWA-TV/rules-processor/blob/master/renderers_html.py#L1101

**Comment by matthewmarks-bbc** [comment]
@bgilmer77 When the website has been updated, please tick the boxes and close the issue.

**Comment by thomasheritage** [comment]
Will be picked-up by planned website updates
