### ISSUE TITLE
AS-11 X3 X4 AVC Property values

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#13]
[AS-11 X3 X4 Parameters.docx](https://github.com/AMWA-TV/AS-11_Overview/files/126207/AS-11.X3.X4.Parameters.docx)
I've attached a table showing the key paramteres for AVC Long GOP, and would like to confirm the correct references and allowable values, and if there is any outstanding detail still needed, (recognising that the update to 4:2:2 sampling is still in progress).

**Comment by thomasheritage** [comment]
Stored height we would make 1080 not 1088
