### ISSUE TITLE
Investigate adding a new Spec for SD International programs (AS-11 X7?)

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#14]
@philtudor and @bgilmer77 -- Presumably this new Specification needs to be formally proposed by @kevinburrows ? Are you able to clarify the process he needs to go through?

[I've provided some ideas / thoughts on the technical details of the new Spec](https://github.com/AMWA-TV/AS-11_Overview/files/126389/AS-11.X7.thoughts.pptx)

@mglanville -- Do you have any comments on the technical details?

**Comment by mglanville** [comment]
The general overview looks right to me.

On the "Misc Content Constraints":
* the AS-11 Regionalisation group asked for AFD 15 to be added to the list

**Comment by thomasheritage** [comment]
Agreed that:
* The overall structure will be as per Slide 1
* In the Misc Content Constraints we will keep the AFD and channel validity constraints but not the others
* We will add a statement about the default audio layout: Channels 1 & 2 are L&R respectively of Stereo Main Programme
* The XML document that is embedded will just be the normal Programmes one -- no Audio Layout / languages details added

**Comment by thomasheritage** [comment]
This is now ready for @mglanville to implement as a new Spec

However, we do still need to follow up on:
> @philtudor and @bgilmer77 -- Presumably this new Specification needs to be formally proposed by @kevinburrows ? Are you able to clarify the process he needs to go through?

**Comment by bgilmer77** [comment]
Kevin can send me an email. List project scope, proponents, business value/purpose and resources available. Simple

**Comment by thomasheritage** [comment]
@kevinburrows has emailed @bgilmer77 

@bgilmer77 to create the GitHub repo for X7 once the new project is confirmed

**Comment by bgilmer77** [comment]
AMWA Board approved this project.  I have created a new project on github and am closing this issue.
