### ISSUE TITLE
Multichannel Audio (MCA) Labels: VisuallyImpairedNarrativeAudioChannel	MCA Tag Name

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#143]
e.g. see https://amwa-tv.github.io/AS-11_X1/AMWA_AS_11_X1.html#2f41d1241c4a3beadcbe7f82606f23b0

The MCA Tag Name is given as "Visually Impaired Narrative" but I think it should probably be "Visually Impaired-Narrative"

**Comment by thomasheritage** [comment]
Per #139 it might be best to recognise that this MCA Tag Name discrepancy is just one of several differences between how AS-11 X* Specifications use MCA and (emerging) practice in IMF (and elsewhere). An alternative is to change the AS-11 X* Specifications.

**Comment by thomasheritage** [comment]
It might be useful to add a short warning in the table in https://amwa-tv.github.io/AS-11_X1/AMWA_AS_11_X1.html#2f41d1241c4a3beadcbe7f82606f23b0 that in IMF & DCP this value contains a "-" (probably easier to do this than in a Note, but could include a Note with more explanation as well).
A similar comment could be added to bmx code.

**Comment by Matthew-Marks** [comment]
Issue created in bmx.

**Comment by Matthew-Marks** [comment]
Comment added to code - bmx issue resolved.

**Comment by thomasheritage** [comment]
Further research demonstrating that the MCA Tag Name used in AS-11 is wrong:
* Table 1 of SMPTE ST 428-12:2013 has a line-break in an unfortunate place, but the text below the table shows "Visually Impaired-Narrative"
* [asdcplib contains "Visually Impaired-Narrative"](https://github.com/cinecert/asdcplib/blob/4e0891ab9ee94b822043126ea07e97641015e9b7/src/MXF.cpp#L1808)
* The [SMPTE DCP test package](https://www.smptedcp.com/resources/test-package) uses "Visually Impaired-Narrative"

**Comment by thomasheritage** [comment]
Conclusions: remaining actions to resolve this issue:
* [x] add a short warning in the table in https://amwa-tv.github.io/AS-11_X1/AMWA_AS_11_X1.html#2f41d1241c4a3beadcbe7f82606f23b0 that in IMF & D-Cinema / DCPs this value contains a "-" (probably easier to do this than in a Note, but could include a Note with more explanation as well). Presumably this will update all AS-11 X* specs (in a non-substantive way)

**Comment by Matthew-Marks** [comment]
https://amwa-tv.github.io/AS-11_X1/AMWA_AS_11_X1.html#3d97e3e08cb8e36c02692b61d2c4d146 - note URL has changed due to other updates.
