### ISSUE TITLE
Improve explanation of the Specification Blocks Tree in HTML Specification views

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#2]
There is a section called "Understanding the Specification Blocks Tree" in the text and HTML views which explains the letters and the fact that Blocks can have alternative conformance (which is the reason for the "outline" style of some of the letters). To make it clearer we should:
* [x] add a (visual) summary key / legend immediately above the Specification Tree itself
* [x] explicitly state the meaning of "outline" style letters (that is, "conformance" state that is something other than "mandatory")
* [x] slightly modify the text under "Understanding the Specification Blocks Tree" to make it clear that this relates to the Specification Blocks Tree.

Also currently a dark blue and a purple are used for character colors. These colors are too similar on many monitors, so:
* [x] change the colours of the Note icons

**Comment by mglanville** [comment]
Still need to "slightly modify the text under "Understanding the Specification Blocks Tree" to make it clear that this relates to the Specification Blocks Tree.", if that's still relevant.
