### ISSUE TITLE
DM Guidance notes and addition

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#22]
Some proposed changes to the guidance text for clarity, and addition to 3D in the attached document
[AS-11 xml Guidance Notes.docx](https://github.com/AMWA-TV/AS-11_Overview/files/148631/AS-11.xml.Guidance.Notes.docx)

**Comment by kevinburrows** [comment]
I should also add that we need to include guidance for 'Custom' Picture Ratios - H/V pixel count or fractional values

**Comment by thomasheritage** [comment]
In terms of the defined ratios for Picture Ratio I think we will either need to make all of the allowed values specific (such as "1.78:1 Letterbox" in stead of "1.78:1") or keep them all raster-agnostic (as they are at the moment).

Perhaps making them all specific would suit you @kevinburrows ?

**Comment by thomasheritage** [comment]
This is now covered by other more specific issues
