### ISSUE TITLE
Add a 50Mbit/s AVC essence restriction to AS-11 X3 and X4

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#23]
The details of this data rate restriction on the AVC essence need to be fully defined -- when this has been done this restriction can be added to the X3 and X4 Specifications.

**Comment by kevinburrows** [comment]
Proposed restriction - 'The data rate of the AVC essence should be a minimum of 50 Mb/s'

**Comment by mglanville** [comment]
I'll add this:

> "The mean data rate of the Picture Essence is greater than or equal to 50,000,000 bits per second"

> Note: This can be calculated by taking the total size of the Picture Essence stored in the file (in number of bits), dividing by the number of Edit Units in the file (which might be more than the length of the Material Package or Top Level File Package) and then multiplying the result by the Edit Rate.
