### ISSUE TITLE
Add X7 Specification

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#24]
* [x] Discuss practicalities of new Spec in Rules Revision Group and assign a Spec Idenitifer (AS-11 X7)
* [x] Formal project proposal
* [x] AMWA board approval for the new Spec
* [x] Create a Private GitHub repo for the Spec
* [x] Configure new GitHub repo
* [x] Agree outline design for the new Spec
* [x] Create Blocks for new Spec in dev system
* [x] Create full details for the new Spec (title, purpose, example XMLs, etc) in dev system
* [x] Populate GitHub repo for the Spec
* [x] Provide IPR declaration form for the contribution to GitHub
* [x] Make the GitHub project public
* [x] Update the AMWA website to list the details of the new Spec
* [x] Update the Tech Overview PowerPoint on the AMWA website

**Comment by thomasheritage** [comment]
[ ] Need to tweak "title" of new GitHub repo

**Comment by thomasheritage** [comment]
@kevinburrows to add a comment on this issue that he has reviewed this X7 repository contents and is happy for it to be made public.

**Comment by kevinburrows** [comment]
I have reviewed the X7 repository and propose it is now made public

**Comment by kevinburrows** [comment]
Have re-opened issue as closed in error

**Comment by thomasheritage** [comment]
OK thanks -- once the IPR declaration is done this repo can be made public.

@philtudor please could you submit an IPR declaration form for AS-11 X7 -- instead of referring to a ZIP please refer to the first commit on this project using:
```
https://github.com/AMWA-TV/AS-11_X7/commit/3cb1d15238d085c92a6033857df0ddd4a3b0dd16
```

**Comment by thomasheritage** [comment]
All the necessary actions have been taken for AS-11 X7 to be ready to be made public (see the details earlier on this issue).

@bgilmer77 please now make AS-11 X7 public on GitHub.

**Comment by bgilmer77** [comment]
AS-11 X7 is now public

**Comment by thomasheritage** [comment]
@kevinburrows to get the AMWA website updated for AS-11 X7

**Comment by kevinburrows** [comment]
AS-11 X7 links and GitHub page now in place
