### ISSUE TITLE
Rawgit to handle mimetypes for XSD and Python

### ISSUE THREAD

**Issue by mglanville** [AMWA-TV/AS-11_Overview#27]
Rawgit has a whitelist of filename extensions that it will proxy. All others are redirected to raw.githubusercontent.com, which always serves content with `Content-Type:text/plain;`.

Rawgit's default whitelist does not include `.xsd` and `.py`. We use both of these in the Specifications. Hence, we'd like them added to rawgit's config so they are served with the correct HTTP headers to allow "friendly" rendering in web browsers.

@bgilmer77 can you action this as detailed below?
## XSD

I believe supporting this is as simple as:
1. adding `.xsd` to the `extensionWhitelist` in rawgit's `conf/index.js`

The correct Content-Type is already included in [mime-db](https://github.com/jshttp/mime-db), which rawgit uses.
## Python

Supporting `.py` is slightly more involved. 
1. `.py` also has to be added to the `extensionWhitelist` in rawgit's `conf/index.js`
2. the code snippet below must be added to rawgit's `conf/mime-types.js`

```
db['text/x-python'] = {
    charset     : 'utf-8',
    compressible: true,
    extensions  : ['py']
};
```
### A note on UTF-8

It is of course possible for Python scripts to be encoded using other character encodings, but all of those in the Blocks world will be UTF-8. Hence it seems useful to include that in the rawgit config. If anyone disagrees with this course of action then we just remove the `charset     : 'utf-8',` line from the code snippet above.

**Comment by bgilmer77** [comment]
These changes have been made.  Please confirm that this now works.

**Comment by thomasheritage** [comment]
Looks good for XML and XSD files at least -- I'll leave @mglanville to confirm.

For various specification_data_files my browser has unfortunately cached (with a timeout of ~30days) the 301 (moved permanently) redirect from amwa.tv/rawgit to raw.githubusercontent.com

**Comment by mglanville** [comment]
Thanks Brad. 

We can't test for `.py` yet because the Specs that use include such files are not public and hence not available via rawgit. 

@thomasheritage that caching behaviour is to be expected. If something is reported as having moved _permanently_, then a browser can reasonably cache that. Let's hope very few people have looked at these files so far and the problem will solve itself in 30 days anyway.

**Comment by mglanville** [comment]
Unassigned as the config has now been applied. I'll keep this issue open until we can test the behaviour for `.py` files, which will be when we make some (currently-private) Specs public.

**Comment by thomasheritage** [comment]
> I'll keep this issue open until we can test the behaviour for .py files, which will be when we make some (currently-private) Specs public.

This has now happened! I've tested and everything is working correctly for `.py` files so this issue can now be closed.
