### ISSUE TITLE
DM XML: Change programme titles

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#28]
Refer to [programme_titles_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/167401/programme_titles_proposal.txt) for the current proposal for replacing the Series, Programme and Episode titles

**Comment by thomasheritage** [comment]
@kevinburrows and @andyquested please review this new proposal  [programme_titles_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/167401/programme_titles_proposal.txt)

**Comment by andyquested** [comment]
Good for me and we can map back to the exsisitng (legacy) DPP names

**Comment by kevinburrows** [comment]
Looks fine with me but I'm just asking for confirmation from the International group

**Comment by kevinburrows** [comment]
Andy, could you please provide a couple of examples of BBC useage for the new fields, eg. a Panarama programme, and an individual film - thanks.

**Comment by andyquested** [comment]
Soap Example
Title 1 EastEnders
Title 2 EastEnders 13324 or EastEnders 17/3/16
Title 3 EastEnders 13324 (not needed but repeated programme name) or EastEnders 13324 Signed

Drama or Doc Single Series
Title 1 Dickensian
Title 2 Diskensian 3 of 20 (or just 3)
Ttiel 3 Dickensian 3 of 20 Post Waterhed

Title 1 Planet Earth
Title 2 Salt Water
Title 3 Salt Water with Making Of

Others 
Title 1 Proms 16
Ttile 2 First Night Preview
Ttile 3 First Night Preview

Title 1 Happy Valley Series 2
Ttile 2 Episode 3 Danger
Ttile 3 Mumbled Version

Title 1 Wimbledon 16
Ttile 2 Highlights
Ttile 3 No captions andf Effects only

**Comment by kevinburrows** [comment]
Thanks for the quick response @andyquested

**Comment by andyquested** [comment]
I filled these exactly the same way I would advise a programme using the current names in the DPP App but mindful of the descritions in the xml Tom posted - hence saying we could easily mapp all legacy programmes
A

**Comment by thomasheritage** [comment]
@kevinburrows has now confirmed that this new proposal is OK
