### ISSUE TITLE
DM XML: Clarify meaning of xs:language type

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#29]
Elements of type `xs:language` use BCP 47 language tags, the details of which are currently set out in RFC 5646. This is [explained by the W3C](https://www.w3.org/International/articles/language-tags/)

However, the [XML Schema Data Types Recommendation](https://www.w3.org/TR/xmlschema-2/) references RFC 3066 which is (indirectly) obsoleted by RFC 5646. Therefore it's not immediately obvious that BCP 47 must be followed for langauge tags in XML Schema.

A Note should be added somewhere to help implementers / users with this (with a link to https://www.w3.org/International/articles/language-tags/ )

**Comment by mglanville** [comment]
Case-sensitivity is another topic this note should cover.

The definition of [the `language` datatype in XML Schema **1.1**](https://www.w3.org/TR/xmlschema11-2/#language) actually includes a note discussing the issue. However, I'm reluctant to link to both versions of the XML Schema Recommendation from the same note (even though the definitions of the type are identical). Hence I'll just reproduce the apposite points of that note in our note.

**Comment by mglanville** [comment]
Following discussion with @thomasheritage we will:
* add a wrapper type named `bcp47_language_tag` (or similar) that is a "null restriction" on `xs:language`  and whose description includes the text "an IETF BCP 47 language tag" 
* use that type in place of `xs:language`
