### ISSUE TITLE
Add AS-11 X8 (NABA MPEG-2)

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#33]
- [x] Discuss practicalities of new Spec in Rules Revision Group
- [x] Formal project proposal
- [x] AMWA board approval for the new Spec
- [x] Assign a Spec Idenitifer (AS-11 X8)
- [x] Agree listing details for the new Specification (title, description, etc)
- [x] Update the AMWA website to list the basic details of the new Spec
- [x] Create a Private GitHub repo for the Spec
- [x] Configure new GitHub repo
- [x] Agree outline design for the new Spec
- [x] Create Blocks for new Spec in dev system
- [x] Create full details for the new Spec (title, purpose, example XMLs, etc) in dev system
- [x] Populate GitHub repo for the Spec
- [x] Provide IPR declaration form for the contribution to GitHub
- [x] Make the GitHub project public
- [x] Update the AMWA website to list the full details of the new Spec
- [ ] Update the Tech Overview PowerPoint on the AMWA website

**Comment by thomasheritage** [comment]
@bgilmer77 please could you create an empty, private repo for AS-11_X8 so that we have it ready

**Comment by bgilmer77** [comment]
Done

**Comment by thomasheritage** [comment]
@ClydeSM to add a comment on this issue that he has reviewed this X8 repository contents and is happy for it to be made public.

**Comment by thomasheritage** [comment]
@philtudor please could you submit an IPR declaration form for AS-11 X8 -- instead of referring to a ZIP please refer to the first commit on the AS-11 X8 project using:

```
https://github.com/AMWA-TV/AS-11_X8/commit/b8229b8f9eb851465ea6ab0c803de5361366cc72
```

**Comment by thomasheritage** [comment]
@ClydeSM has confirmed by email that AS-11 X8 is ready to be made public and @philtudor has provided the IPR declaration. So, @bgilmer77 please could you make the repo public.

**Comment by thomasheritage** [comment]
This final item ("Update the Tech Overview PowerPoint on the AMWA website") is covered by #95
