### ISSUE TITLE
Add AS-11 X9 (NABA AVC)

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#35]
- [x] Discuss practicalities of new Spec in Rules Revision Group
- [x] Formal project proposal
- [x] AMWA board approval for the new Spec
- [x] Assign a Spec Idenitifer (AS-11 X9)
- [x] Agree listing details for the new Specification (title, description, etc)
- [x] Update the AMWA website to list the basic details of the new Spec
- [x] Create a Private GitHub repo for the Spec
- [x] Configure new GitHub repo
- [x] Agree outline design for the new Spec
- [x] Create Blocks for new Spec in dev system
- [x] Create full details for the new Spec (title, purpose, example XMLs, etc) in dev system
- [x] Populate GitHub repo for the Spec
- [x] Provide IPR declaration form for the contribution to GitHub
- [x] Make the GitHub project public
- [x] Update the AMWA website to list the full details of the new Spec
- [ ] Update the Tech Overview PowerPoint on the AMWA website

**Comment by thomasheritage** [comment]
@bgilmer77 please could you create an empty, private repo for AS-11_X9 so that we have it ready

**Comment by bgilmer77** [comment]
Done

**Comment by thomasheritage** [comment]
@ClydeSM to add a comment on this issue that he has reviewed this X9 repository contents and is happy for it to be made public (note that there are some "TODO" items in the Spec particularly in relation to AVC coding details that need to be refined based on practical testing etc &ndash; this is fine since this is a WIP Spec)

**Comment by thomasheritage** [comment]
@philtudor please could you submit an IPR declaration form for AS-11 X9 -- instead of referring to a ZIP please refer to the first commit on the AS-11 X9 project using:
```
https://github.com/AMWA-TV/AS-11_X9/commit/5bb27e84492a8a6e8089ab88f50d91bebab1a31b
```

**Comment by thomasheritage** [comment]
@ClydeSM has confirmed by email that AS-11 X9 is ready to be made public and @philtudor has provided the IPR declaration. So, @bgilmer77 please could you make the repo public.

**Comment by thomasheritage** [comment]
This final item ("Update the Tech Overview PowerPoint on the AMWA website") is covered by #95
