### ISSUE TITLE
DM XML: Decide on nomenclature for Loudness measurement

### ISSUE THREAD

**Issue by mglanville** [AMWA-TV/AS-11_Overview#37]
ITU uses LKFS; EBU uses LUFS. These are different terms for the same concept: Loudness that is K-weighted and measured relative to full scale.

In [R 128](https://tech.ebu.ch/docs/r/r128-2014.pdf) the EBU asserts that LUFS "is compliant with international naming conventions", thereby implying that LKFS is not.

Nevertheless, we should probably use LKFS since that is what [ITU-R BS.1770](https://www.itu.int/rec/R-REC-BS.1770-4-201510-I/en) uses, and most of the Loudness Specifications we enumerate in [`cd:Audio_Loudness_Specification`](http://www.amwa.tv/rawgit/AMWA-TV/AS-11_X2/master/include/specification_data_views/block/DM_Programmes/artefacts/DM_Programmes.html#Content_Details_Content_Details_Audio_Loudness_Details_Audio_Loudness_Specification) are based upon BS.1770.

**Comment by thomasheritage** [comment]
Chang the first sentence of the definition of `Programme_Loudness_Value` to:
> The "Programme Loudness Value" in LKFS (also known as "LUFS") as measured in accordance with the indicated Audio Loudness Specification.

@andyquested and @kevinburrows is this OK?

**Comment by thomasheritage** [comment]
@andyquested and @kevinburrows is this OK?

**Comment by kevinburrows** [comment]
This is good with me Tom

**Comment by thomasheritage** [comment]
@andyquested says this is OK

**Comment by thomasheritage** [comment]
@mglanville please now implement this change
