### ISSUE TITLE
DM XML: refine the definition of Ident_Clock_Start to make it suitable for NABA

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#38]
Make it:
> The timecode at which the initial "ident" / slate / countdown clock begins.

Proposed by @andyquested for the NABA work

Are you happy with this @kevinburrows ?

**Comment by thomasheritage** [comment]
Are you happy with this @kevinburrows ?

**Comment by kevinburrows** [comment]
This change is fine with me Tom

**Comment by thomasheritage** [comment]
@mglanville please now implement this change
