### ISSUE TITLE
DM XML: refine the definition of Programme_Loudness_Value

### ISSUE THREAD

**Issue by mglanville** [AMWA-TV/AS-11_Overview#39]
We currently have this:

> The "Programme Loudness Value" in LUFS as measured in accordance with the indicated Audio Loudness Specification. This is intended to give an indication of the degree to which the content deviates from the indicated Audio Loudness Specification, rather than a precise measurement of the loudness of the content. 

I'd like to propose this:

> The "Programme Loudness Value" in LUFS as measured in accordance with the indicated Audio Loudness Specification. It will not always be possible to reproduce the measurement without further information such as which audio channels were measured, what anchor was used, or if part of the content was excluded from the measurement. This is intended to give an indication of the degree to which the content deviates from the indicated Audio Loudness Specification.

_Note that this change is independent of the proposition in #37 regarding LUFS/LKFS_

@kevinburrows @andyquested - I await your feedback.

**Comment by thomasheritage** [comment]
@kevinburrows @andyquested - I await your feedback.

**Comment by andyquested** [comment]
OK for me - sorry, I missed the first notification, it was probably due the shock of your announcement (about that time) that you were moving on!

**Comment by kevinburrows** [comment]
This is fine with me Tom

**Comment by thomasheritage** [comment]
@mglanville please now implement this change
