### ISSUE TITLE
Defined_Picture_Ratios_type: review enumeration values & documentation

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#4]
Suggestion that "15/9" should be "1.66:1" (15/9 seems to be a UK specific description). Is this OK with all Business Requirements Owners?

**Comment by kevinburrows** [comment]
The following aspect ratios were queried by the International group as not being required, and would like to agree the status with the DPP. 
  
21/9 - an approximation for 64:27 which is the true ratio, (this could have legacy implications however)
1.90:1 - It was not clear where this is standardised or needed.
2.37:1 - as above
2.40:1 - this seems to be an approximation for 2.39:1

Whilst we should include all valid options, we should exclude any which are unlikely to be used

**Comment by thomasheritage** [comment]
We'll convert all the numerical defined ratios to "x:1" with the fraction in the documentation.

**Comment by thomasheritage** [comment]
2.40:1 - keep as 2.40:1 but note in the documentation that this is an approx for 2.39:1

**Comment by thomasheritage** [comment]
"1.90:1" can be removed

**Comment by thomasheritage** [comment]
I've made the changes in the XML snippet stored in [picture_ratios_enum_values_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/134610/picture_ratios_enum_values_proposal.txt)

Is this OK @kevinburrows and @andyquested ?

**Comment by kevinburrows** [comment]
2.37:1 - The only reference to this I can find is for Philips TVs manufactured for a few years, and not a standard film or DCI ratio. Unless there is anything esle we should remove this one. (Andy Q to confirm)

**Comment by andyquested** [comment]
Agree



Andy Quested
Head of Technology BBC HD & UHD
TV Technology
BBC Engineering
BBC | BC4 A4 BBC Broadcast Centre | 201 Wood Lane | London W12 7TP  | UK

Mob:   +44 780 959 7723
Tel:     +44 303 080 3224
________________________________

**Comment by thomasheritage** [comment]
OK so we will remove 2.37. Otherwise are both @kevinburrows and @andyquested happy with [picture_ratios_enum_values_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/134610/picture_ratios_enum_values_proposal.txt) ?

**Comment by thomasheritage** [comment]
Refer to [picture_ratios_enum_values_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/167410/picture_ratios_enum_values_proposal.txt) for an updated proposal

**Comment by thomasheritage** [comment]
@kevinburrows and @andyquested please review this new proposal for Picture Ratio enumeration values:
*  [picture_ratios_enum_values_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/167410/picture_ratios_enum_values_proposal.txt)

Also, @kevinburrows previously said:
> I should also add that we need to include guidance for 'Custom' Picture Ratios - H/V pixel count or fractional values

which we have not yet discussed.

**Comment by andyquested** [comment]
for my informaiton - how do we itentify 1.78:1 full width/full height and 1.33:1 full width/full heightl with differentiating between full width/full height 4:3 and full width/full height anamorphic 16:9

**Comment by kevinburrows** [comment]
Comments from the international group.

'Pillarbox' is not a term used in Australia, New Zealand or the Nordic Countries. A better standardised term is 'Side Bars' which is used in SMPTE documents along with Letterbox

2.40:1 is an approximation for 2.39, so 2.39 should be used in the name, as in SMPTE RP 199 2004 and SMPTE 96M 2004, as below
2.39:1 centred letterbox
2.39:1 (or 2.40:1) picture with black bars. The picture is full width and centred vertically

Unspecified Letterbox, (change to definition)
The picture fills the full width of the frame and there are black bars of unspecified _or unknown _height to the top and bottom of the picture.

Unspecified Side Bars
as above 'unspecified or unknown'....

**Comment by thomasheritage** [comment]
I suggest that we stick with "pillarbox" as it seems to be used quite widely unlike the term "sidebar".

"Pillarbox" seems to be used by:
* [IRT](https://www.irt.de/webarchiv/showdoc.php?z=NzUwMyMxMDA2MDE4I3BkZg==)
* [AVID](http://avid.force.com/pkb/articles/en_US/troubleshooting/Black-borders-may-be-displayed-on-the-sides-and-tops-of-some-movie-files) and [here as well](https://books.google.co.uk/books?id=DFM_G2q6qXgC&pg=PT55&lpg=PT55&dq=avid+pillarbox&source=bl&ots=opA17RjOFc&sig=_n5qI2zUuHU3Wrf495Hmqvqfowg&hl=en&sa=X&ved=0ahUKEwiRosmEhtLLAhUBNhoKHeE_DdUQ6AEIQjAE#v=onepage&q=avid%20pillarbox&f=false)
* [EBU QC Group](http://ebu.io/qc/items/0001W/versions/2-0/)
* [BlackMagic](https://www.blackmagicdesign.com/gb/products/ultrastudiothunderbolt/techspecs)
* [Apple](https://support.apple.com/en-us/HT204429)
* [EBU Subtitling Definitions](https://tech.ebu.ch/docs/tech/tech3350.pdf)
* SMPTE ST 380
* SMPTE ST 2016-1 (The definition of AFD values as referenced by AS-11 Specs -- it does mention that "sidebar" can be an alternative for Pillarbox but uses Pillarbox as its main term)
* SMPTE ST 2046-1
* SMPTE RP 2002

**Comment by thomasheritage** [comment]
1. Please review the updated proposal: [picture_ratios_enum_values_proposal.txt](https://github.com/AMWA-TV/AS-11_Overview/files/186689/picture_ratios_enum_values_proposal.txt)
2. The Custom_Picture change is now at #32
3. "Pillarbox" term. Below are some more examples of uses of the term "Pillarbox". @kevinburrows please do carry out further research if you wish and report back. I'm not expecting anyone else to research this further.

Other uses of "Pillarbox":
* [CBC / Radio Canada](http://www.cbc.radio-canada.ca/_files/cbcrc/documents/reporting-to-canadians/tech-standards/technical-specs-for-program-delivery.pdf)
* [NAB paper from NBC-Universal](https://www.nab.org/documents/resources/paperHau.pdf)
* [FREE TV AUSTRALIA OPERATIONAL PRACTICE 53](http://www.freetv.com.au/media/Engineering/OP53_Issue_3_-_File_Delivery_Format_for_evaluation_and_assessment.pdf)
* [PBS Tech Operating Specifications for Distribution](http://bento.cdn.pbs.org/hostedbento-prod/filer_public/PBS_About/Producing/Red%20Book/tos%202013%20pt2%20distribution%2010_18_13.pdf)

**Comment by thomasheritage** [comment]
More uses of "Pillarbox":
* IMF [Plugfest](http://www.imfforum.com/IMF_Forum/plugfest.html) documentation in the [definitions of the test files being used](http://imfforum.com/papers/technical-objectives-imf-plugfest-ams-2015.pdf)
* Hollywood (according to @andyquested )

**Comment by thomasheritage** [comment]
We will stick with "Pillarbox", so no need to change the .txt proposal -- now ready to put into XML Schema. Agreed by @andyquested and @kevinburrows
