### ISSUE TITLE
Picure Ratio, unspecified Leterbox and Pillarbox

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#41]
An outstanding minor change to the description to allow for uneven centreing, (**s** below)

Centred letterbox 	
The picture fills the full width of the frame, is vertically centred in the frame and there are black bars of unspecified (perhaps unknown) height**s** to the top and bottom of the picture
	
Centred pillarbox 	
The picture fills the full height of the frame, is horizontally centred in the frame and has black bars of unspecified (perhaps unknown) width**s** to the left and right of the picture

Unspecified letterbox 	
The picture fills the full width of the frame and there are black bars of unspecified (perhaps unknown) height**s** to the top and bottom of the picture. The black bars may not be of equal height (and so the "letterbox" may not be vertically centred)

Unspecified pillarbox 	
The picture fills the full height of the frame and there are black bars of unspecified (perhaps unknown) width**s** to the left and right of the picture. The black bars may not be of equal width (and so the "pillarbox" may not be horizontally centred)

**Comment by thomasheritage** [comment]
@mglanville please now implement this change
