### ISSUE TITLE
DM XML: Allow drop-frame timecode notation for durations

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#45]

**Comment by thomasheritage** [comment]
@kevinburrows agrees with this change

**Comment by thomasheritage** [comment]
@andyquested -- are you also OK with this small change (allowing the use of drop-frame timecodes in the XML when stating durations)? We want this for X8 and X9

**Comment by andyquested** [comment]
yep - it's a must have really!
