### ISSUE TITLE
AS-11 X3 & X4: constrain GOP length

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#48]
The AVC Maximum GOP Size is 1 second.

**Comment by andyquested** [comment]
Why?

**Comment by thomasheritage** [comment]
@kevinburrows requested this change so you would have to ask him @andyquested

**Comment by andyquested** [comment]
OK. Kevin, why would we need to constrain a GoP length in an air master?

**Comment by kevinburrows** [comment]
There is still a requirement to re-version, and 1 second fits well with the current Sony and Panasonic implementations for 1080p. Leaving GOP length totally open would leave us vulnerable.

**Comment by kevinburrows** [comment]
Issue still open

**Comment by andyquested** [comment]
OK - assume this will be a GoP length constraint that only applies to X3 & X4 or could it change if a SMPTE "version" were to include content dependant variable?  Also, do we know if the RDD for Ultra will be constrained?

**Comment by kevinburrows** [comment]
This is only intended for X3 and X4, I assume that X1 may be different
AVC Ultra GOP lengths are
60 frames - 59.94p
48 frames - 50p
24 frames - 25p, 23.98p

**Comment by andyquested** [comment]
many thanks and understand - I have no problem now
