### ISSUE TITLE
Review AVC Levels that are stated

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#49]
Check that the Levels given are correct: the maximum bitrate does depend on the Profile that is used. For example, for AS-11 X3 we think that the correct answer might be "at least Level 4 or 4.2" rather than "at least Level 4.1 or 4.2".

**Comment by thomasheritage** [comment]
I've reviewed possible AVC Levels for AS-11 X3 and X4, as below. The other Specs are fine for now as they require more AVC details anyway.

@kevinburrows do we want to mandate that in each case the "lowest possible level" is the one that is used? (so use of Level 4.2 would be prohibited if it's possible to use Level 4) (this will at least affect the Level that can be signalled in the AVC stream, if nothing else)

## AS-11 X3

We have:
* 1080p/25 or 1080p/50
* AVC Byte Stream Format
* High 4:2:2 Profile

For 1080p/25 -- Level 4 is the lowest possible level and would require:
* MaxDpbFrames is 4
* At least four coded slices per video frame
* "BitRate" <=96Mbits/s
* "CpbSize" <= 130Mbits

For 1080p/50 -- Level 4.2 is the lowest possible level and would require:
* MaxDpbFrames is 4
* At least four coded slices per video frame
* "BitRate" <=240Mbits/s
* "CpbSize" <= 300Mbits


## AS-11 X4

We have:
* 1080p/23.98 or 1080p/59.97
* AVC Byte Stream Format
* High 4:2:2 Profile

For 1080p/23.98 -- Level 4 is the lowest possible level and would require:
* MaxDpbFrames is 4
* At least four coded slices per video frame
* "BitRate" <=96Mbits/s
* "CpbSize" <= 130Mbits

For 1080p/59.97 -- Level 4.2 is the lowest possible level and would require:
* MaxDpbFrames is 4
* At least four coded slices per video frame
* "BitRate" <=240Mbits/s
* "CpbSize" <= 300Mbits

**Comment by kevinburrows** [comment]
It is proposed that the use of Level 4.2 is 'recommended' where possible.

**Comment by thomasheritage** [comment]
## Decision from meeting today
For 25 and 23.98 must use Level 4, 4.1 or 4.2

For 50 and 59.94 must use Level 4.2

**Comment by thomasheritage** [comment]
:arrow_right: This might work as a practical solution in the Rules-based Components:
* Remove http://vm-1274-user.virt.ch.bbc.co.uk/as/note/E20/ from http://vm-1274-user.virt.ch.bbc.co.uk/as/block/PEC_4/ and http://vm-1274-user.virt.ch.bbc.co.uk/as/block/PEC_5/
* Add a new Block to each of http://vm-1274-user.virt.ch.bbc.co.uk/as/block/PEC_4/ and http://vm-1274-user.virt.ch.bbc.co.uk/as/block/PEC_5/ -- this new Block would say the AVC Level must be less than or equal to Level 4.2
* Attach a note to PEC_4 and PEC_5 that explains what the allowed Levels are (as  above) for the frame rates that are pertinent to the Specification (probably using the new notation for frame rates as per #73 )
