### ISSUE TITLE
Do we need to support having an Audio Loudness Test Result for each Sound Track?

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#5]
At the moment multiple "Audio_Loudness_Test"s are permitted but there is no way to tie each result to the Sound Track whose Loudness was measured.

Is there a requirement for this?

Or perhaps we could remove the "Programme_Loudness_Value" and say that any "Audio_Loudness_Test" applies to all the Audio in the MXF file.

**Comment by thomasheritage** [comment]
Remove `Audio_Loudness_Test_Results` Element from the XML

Add `Audio_Loudness_Details` as mandatory (there is one of these in the XML for the entire MXF file)

Inside `Audio_Loudness_Details` we have the existing three fields. We also add an `explanation` field in which you can explain why you are not compliant if that is the case.

Loudness Value is an approximate indication of the TX-able (finished) Audio Tracks in the MXF file.

The `Audio_Loudness_Details` capture information about what Audio Loudness Spec the programme maker was working to -- this applies to the finsihed (TX-able) audio in the MXF file. (Not  to specific Audio Tracks on their own)

(Don't mention audio loudness "tests" at all)

**Comment by thomasheritage** [comment]
This means that Programme Audio Is Intentionally Quiet won't be needed

**Comment by mglanville** [comment]
Given that we're changing the meaning of the `Audio_Loudness_Specification` element, I'm going to remove some of the enumeration facets (those that specify only the method of measurement, not any targets for loudness, true peak, etc.):
* ~~ITU-R REC BS.1770~~
* ~~EBU Tech 3341~~
* EBU R 128
* EBU R 128 s1
* ITU-R REC BS.1864
* FreeTV OP-59
* FreeTV OP-48 :eight_spoked_asterisk: 
* ATSC A/85 (Dialog Anchor)
* ATSC A/85 (Full Program mix Anchor)
* ATSC A/85 (Unspecified Anchor)

:eight_spoked_asterisk: can someone (@kevinburrows?) please confirm that OP-48 is needed. It's not a "Loudness" specification in the ITU BS.1770 sense, but it does give general guidance on audio levels and loudness. It probably fits better with our redesigned loudness DM than it did with the previous arrangement, but I'd like to confirm that it is still relevant as a requirement for programme delivery, now that OP-59 exists.

**Comment by thomasheritage** [comment]
Just re-opening as it would be good to confirm the additional changes (the removal of the enumeration values).

**Comment by thomasheritage** [comment]
Also, is there a dependency between `Compliance_To_Specification_Achieved` and `Explanation`? Perhaps we want to address this by a nested structure as has been used elsewhere

**Comment by kevinburrows** [comment]
I can confirm that Free TV OP48 is very much needed, OP59 is not currently the primary legal document

**Comment by mglanville** [comment]
I'll move `Explanation` to sit under `Compliance_To_Specification_Is_Not_Achieved` (with a `xs:choice` for `Compliance_To_Specification_Is_Achieved`)

I'll change `ATSC A/85 (Unspecified Anchor)` to `ATSC A/85 (Other Anchor)` as "unspecified" doesn't really cover what we mean.

**Comment by mglanville** [comment]
Thanks @kevinburrows - I thought that might be the case.

**Comment by thomasheritage** [comment]
This has now all been implemented.

For reference, ![this is what this part of the XSD now looks like](https://cloud.githubusercontent.com/assets/5365792/13147754/062c324a-d652-11e5-93a5-ee1b42d51fe7.png)

@andyquested might want to just check that this looks as he expected

**Comment by thomasheritage** [comment]
@andyquested please confirm that you are happy with the Loudness details as they are now in the XML Descriptive Metadata

**Comment by andyquested** [comment]
Sorry for the delay - yes.  Assuming we are not allowing PPM mixes on new programme the route works for all content.  Pre R128 content will need to say so - post non compliant must the case by case agreed

**Comment by andyquested** [comment]
As the QC process confirms each TX  services (tracks) is compliant a single "file is complaint" is all that's needed

**Comment by thomasheritage** [comment]
@andyquested agreed that this issue is now resolved
