### ISSUE TITLE
X3 & X4 AVC Encoded bit rate

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#51]
The current AVC encoded stream wording 'The mean data rate of the picture essence is greater than or equal to 50,000,000 bits per second' to be replaced with the following proposed wording
The maximum datarate of the encoded picture essence shall be no higher than 75 Mbps, and the average datrate should be 50 Mbps. The stream should be encoded as VBR.

**Comment by andyquested** [comment]
Sounds reasonable - what would happen on a "slow TV wander through the snow" though!!  Might struggle for an average to 25 let alone 50:)

**Comment by kevinburrows** [comment]
It's not mandatory to allow for this, unlike the maximum

**Comment by andyquested** [comment]
:)  would it be better to say ....and the average datarate should normally be 50 Mbps...

**Comment by kevinburrows** [comment]
Unfortunately that's not the case for Sony XAVC which is a maximum of 50 Mbps....

**Comment by andyquested** [comment]
As usual driven by Sony

**Comment by thomasheritage** [comment]
## Suggestion

Mandatory:
* The maximum datarate of the encoded picture essence is no higher than 75 Mbps. This calculation:
  * takes into account all stored essence (i.e. including pre-charge and roll-out)
  * involves dividing the essence into consecutive 1 second chunks and summing the number of bits used in each chunk. The number of bits used in each chunk must not be more than 75Mbits.

Recommended:
* The mean data rate of the Picture Essence is 50 Mbps (so this is the total size of the stored picture essence in the whole file divided by the number of seconds)
* The stream is VBR -- what does VBR mean though?

**Comment by thomasheritage** [comment]
Basically go with this except instead of VBR say "no padding" in the AVC

**Comment by kevinburrows** [comment]
For the mean data rate,

For quality reasons the mean data rate of the Picture Essence should be 50 Mbps, and this ahould minimise the level of padding in the stream.

**Comment by thomasheritage** [comment]
## Suggestion (Updated)

Mandatory:
* The maximum datarate of the encoded picture essence is no higher than 75 Mbps. This calculation:
  * takes into account all stored essence (i.e. including pre-charge and roll-out)
  * involves dividing the essence into consecutive 1 second chunks and summing the number of bits used in each chunk. The number of bits used in each chunk must not be more than 75Mbits.

Recommended:
* The mean data rate of the Picture Essence is 50 Mbps (so this is the total size of the stored picture essence in the whole file divided by the number of seconds)
* There is no padding in the AVC stream

NOTE:
* These constraints are designed to achieve the desired quality while keeping the file size at an acceptable level.
* This means that the AVC stream will almost certainly have a "variable bit rate"

**Comment by kevinburrows** [comment]
For clarity it is proposed to chage the following as the absolute quality is not referenced anywhere.These constraints are designed to achieve **a** desired **video** quality (rather than 'the')

**Comment by thomasheritage** [comment]
OK.

:arrow_right: Change text of http://vm-1274-user.virt.ch.bbc.co.uk/as/note/E70/ to:
> This constraint is designed to achieve a desired video quality while keeping the file size at an acceptable level.
