### ISSUE TITLE
X3 and X4 GOP Structure

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#52]
Proposed wording for GOP Structure.

The structure of the AVC Long GOP encoded stream shall be constrained to SMPTE 381-3 Annex C, Figure C.1

- All P Pictures consist of only P-Slices and all B Pictures or Br Pictures consist of only B-Slices.
- The first access unit in coded order is an IDR or non-IDR I Picture in GOP and a sequence parameter set and a picture parameter set are present in the first access unit of each GOP.
- For each picture in the GOP, the corresponding Key Picture is present within the same GOP or the
immediately preceding GOP.
- A P Picture does not refer to a B Picture.
- The coded order for all I- and/or P Pictures is the same as their display order.
- The coded order for non-reference B Pictures that are contiguous in the bit stream is the same as their display order.

Proposed associated Implementation Note
The use of the C.1 structure for AVC long GOP encoded streams for MXF wrapping provides fast access to target pictures and reduces decoder complexity.

**Comment by thomasheritage** [comment]
Fig C.1 is an example implementation that meets the stated restrictions. We need to clarify the exact structure used in Fig C.1 in order to use it as the basis of a constraint for these AS-11 specifications. And we need to clarify whether the example has to be followed literally i.e. GOP has to always have 12 frames.

**Comment by kevinburrows** [comment]
C1 is an example structure only, following the Annex C wording, and should not constrain the GOP to 12 frames. We can refer to our constraint already included that the maximum GOP length should be 1 second.

**Comment by thomasheritage** [comment]
## Suggestion

* The AVC stream is constrained as per Annex C of SMPTE ST 381-3:2013
* No B picture is a reference picture

NOTE:
* This rules out Figure C.2 -- the expectation is that streams will be similar to the example given in Figure C.1

**Comment by kevinburrows** [comment]
**Updated proposed wording**

- The AVC stream is constrained as per Annex C of SMPTE ST 381-3:2013
-  No B picture is a reference picture

NOTE:

The intention is that streams will be similar to the example given in Figure C.1. The constraint of no B picture being a reference picture excludes Figure C.2

**Comment by kevinburrows** [comment]
Following correspondance with Panasonic and Sony,

Remove the constraint 
'No "B Picture" is a reference picture'

Update the Implementation note 
'This constrains the GOP structure and length. The intention is that streams will be similar to the example given in Figure C.1 **or C.2** of SMPTE ST 381-3:2013'
