### ISSUE TITLE
Clarify the purpose of the "ID" under Additional Info in the HTML rendering

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#55]
This "ID" is a URL that is the "ID" of the Rules Framework Component. However, it should be made clear that the URL may not be resolvable and may not be publicly accessible -- it's principal purpose is to act as an ID for the Component. Even if it is resolvable, it will usually resolve to the "raw" back-end Rules Framework Component file which is probably not of interest to anyone except Specification authors. To be clear, it is never necessary to click on an "ID" link under "Additional Information" in an HTML rendering of an AMWA AS-11 Rules-based Specification -- all the information required to understand and implement such as Specification is included within the Specification GitHub repository and is publicly accessible.

The intention is that "approved" Components (in Proposed Specifications and above) will have AMWA URLs and be publicly accessible using their IDs.

**Comment by matthewmarks-bbc** [comment]
Suggest at least making the URLs inactive.

**Comment by thomasheritage** [comment]
Resolved by commits across all the AS-11 Specs today (changes have been made to how this information is presented)
