### ISSUE TITLE
X7 elevation to proposed specification

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#58]
In order to qualify for elevation to proposed specification, could I have details of any testing which has been undertaken to date with the created sample file? 

New Zealand are hoping to carry out some testing and it would be useful to know what has been done so far.

**Comment by thomasheritage** [comment]
The X7 sample MXF file has been tested in our lab in the same way as AS-11 UK DPP SD MXF files are (informally) tested. All the tests were passed (except for the embedded DM tests of course).

I am not aware of any other testing or investigation that has been carried out.

@kevinburrows -- can this issue be closed now?

**Comment by kevinburrows** [comment]
This issue can be closed now
