### ISSUE TITLE
Make the setting of the "Drop Frame" property to True for US Frame rates mandatory

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#59]
This is currently "Recommended" but we are considering making it "Mandatory" instead.

@clydesm has agreed that this is position we want to take for X8 and X9

@kevinburrows is going to check about this for X4

**Comment by thomasheritage** [comment]
@andyquested this does not have any practical impact on your Specifications (because they don't use US frame rates -- I mean 29.97 and 59.94) although the altered text will appear within all the new AS-11 Specifications (because it's part of a shared building block).

However, if you can think of any reason why, for an air-ready file, someone using US frame rates would ever want to use _non_ drop frame timecode then let us know...

**Comment by kevinburrows** [comment]
Agree that this should be made mandatory for X4

For clarity it is proposed that a note is added that for 24/1.001 fps this should be signalled as 'False' as drop frame timecode is not applicable to this frame rate.

**Comment by thomasheritage** [comment]
:arrow_right: These changes are needed:

1) In http://www.amwa.tv/projects/rules/01/block/TT0/ change the conformance of http://www.amwa.tv/projects/rules/01/block/DF/ from "Recommended" to "Mandatory". This change is to an AMWA Component and **does** need an ID change.

2) Add a Note titled "Implementation Notes" to http://www.amwa.tv/projects/rules/01/block/DF/ below the existing Note. In this Note say:
> Note that for an "Edit Rate" of `24000/1001` the "Drop Frame" property will be "False" because drop frame timecode is not applicable to this rate

This change will create a new AMWA Component (Note) and edit an existing AMWA Component (Block) -- this edit does **not** need an ID change.

**Comment by thomasheritage** [comment]
Thanks @philipnbbc 

However, I notice that this is linked into AS-11 X8 in a different way. So, the following additional change is required:
* In http://vm-1274-user.virt.ch.bbc.co.uk/as/block/TT1/ change the conformance for http://www.amwa.tv/projects/rules/01/block/DF/ from "recommended" to "mandatory" -- an ID change is **not** required as this is not an AMWA component.

This only affects AS-11 X8
