### ISSUE TITLE
Elevate AS-11 X2 from WIP to Proposed Specification

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#65]
* [x] Submit formal request for elevation (triggers a review)
* [x] Receive confirmation that elevation has been authorised
* [x] Change the IDs of WIP Rules Framework Components to use formal AMWA URLs
* [x] Make any changes within the Specification related to the ID change (e.g. the ID change may change an XSD namespace and so example XML files might need to be updated)
* [x] Update the Specification Identifiers specified for inclusion in the MXF file, as appropriate
* [x] Change the Specification status from "[Work In Progress]" to "[Proposed Specification]"
* [x] Create a Tag / Release of the Specification
* [ ] Update the Specification page on the AMWA website
* [x] Announce the Specification elevation & the tag / release
* [x] Update any sample MXF files
* [x] Make any changes elsewhere related to the ID change (e.g. any other tutorial material or online AS-11 tools might need to be updated)

**Comment by thomasheritage** [comment]
"Update any sample MXF files" is covered by #63 so is marked completed

**Comment by kevinburrows** [comment]
AS-11 and AS-11 X2 pages are now updated on the AMWA website

**Comment by thomasheritage** [comment]
@kevinburrows reported today that he is still to action the final website change: this will involve adding a note to each AS-11 X Specification page to link to the "releases" page for each Spec on GitHub.

**Comment by kevinburrows** [comment]
This is now complete
