### ISSUE TITLE
Elevate AS-11 X7 from WIP to Proposed Specification

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#66]
* [x] Submit formal request for elevation (triggers a review)
* [x] Receive confirmation that elevation has been authorised
* [x] Change the IDs of WIP Rules Framework Components to use formal AMWA URLs
* [x] Make any changes within the Specification related to the ID change (e.g. the ID change may change an XSD namespace and so example XML files might need to be updated)
* [x] Update the Specification Identifiers specified for inclusion in the MXF file, as appropriate
* [x] Change the Specification status from "[Work In Progress]" to "[Proposed Specification]"
* [x] Create a Tag / Release of the Specification
* [x] Update the Specification page on the AMWA website
* [x] Announce the Specification elevation & the tag / release
* [x] Update any sample MXF files
* [x] Make any changes elsewhere related to the ID change (e.g. any other tutorial material or online AS-11 tools might need to be updated)

**Comment by kevinburrows** [comment]
Elevation to proposed specification has now been authorised and the IDs can now be changed and the release tagged in Github.

**Comment by thomasheritage** [comment]
AMWA website changes needed:
* On http://amwa.tv/projects/AS-11-X7.shtml change Maturity Level of "Latest development version" to `Proposed Specification`
* On http://amwa.tv/projects/AS-11.shtml change Publication Status / Maturity Level to `Published as 'Proposed Specification'`

**Comment by thomasheritage** [comment]
"Update any sample MXF files" is covered by #63

**Comment by thomasheritage** [comment]
The [online AS-11 inspection tool](https://vm-1462-user.virt.ch.bbc.co.uk/pages/regxmldump_as11.html) needs to be updated -- covered by #76
