### ISSUE TITLE
Change "datarate"-->"data rate" in Note

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#72]
This note:  http://www.amwa.tv/projects/rules/01/note/E10/

**Comment by andyquested** [comment]
Not sure this makes sense - assuming 1080p/25 is <=96Mb/s then 1080p/50 would only be around 20% more surely???

**Comment by thomasheritage** [comment]
@andyquested I don't think you meant to comment on this issue... Did you mean to comment on #49 ?

**Comment by thomasheritage** [comment]
This is an AMWA Note but no ID change is required
