### ISSUE TITLE
'Additional Information' headings

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#77]
The headings titled 'Additional Information' contain the AMWA URLs, and the title has caused confusion by people thinking there are further descriptive notes behind this. Also clicking on the link requires a password which is the subject of another open issue.

Could 'Additional Information' be renamed as 'AMWA URL' to make it clear what these actually are.

**Comment by thomasheritage** [comment]
Related to #55 

I will look at how to resolve this situation -- thanks for reporting that this is causing confusion

**Comment by thomasheritage** [comment]
Resolved by commits across all the AS-11 Specs today (changes have been made to how this information is presented)
