### ISSUE TITLE
AS-11 X1: reference ITU-R BT.2100 instead of BT.2020

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#79]
Related updates will also be needed in AS-11 X1 e.g. in relation to HDR transfer characteristics details / comments and their specified signalling in H.264 and MXF.

The constraints / profiling of BT.2100 should also be reviewed -- it looks like frame sizes and colour spaces might need to be permitted in AS-11 X1 that are not currently allowed. For discussion with @andyquested

**Comment by thomasheritage** [comment]
In the current AS-11 X1 (DPP UHD) sample files (uses the Edinburgh Tattoo BBC UHD HLG sample material) we signal the following – confirm this is still correct:
* `TransferCharacteristic_HLG_OETF` (references ITU-R BT.2100)
* `CodingEquations_ITU2020_NCL` (NCL=Non-constant Luminance)
* `ColorPrimaries_ITU2020`

**Comment by andyquested** [comment]
Just wondering if we should quote the primaries as BT.2100 too – agreed they are a cut and paste from BT.2020 but things may change and BT.2020 might just disappear one day


A


Andy Quested
BBC Design and Engineering
BBC | BC4 A4 BBC Broadcast Centre | 201 Wood Lane | London W12 7TP  | UK

Mob:   +44 780 959 7723
Lync:  +44 303 080 3224

**Comment by thomasheritage** [comment]
We should consider whether to mandate the exact signalling to be used (i.e. which Labels to use) so that there is no ambiguity.

**Comment by thomasheritage** [comment]
@matthewmarks-bbc -- a reminder that there is this outstanding X1 clean-up to do related to HDR signalling in MXF and HDR. This would be worth doing sooner rather than later.

AS-11 X1 maybe should mandate inclusion of the MXF Header Metadata properties Black Ref Level, White Ref Level and Color Range -- I believe that these were not included before because they were not of core concern. However, they do provide clarity over whether the video is "full range" or not (which is particularly useful given some confusion in HD and the fact that "full range" and non-"full range" are given as options in 2100). Also, I think that Color Range doesn't default to the correct value if not included (this needs verifying).

Note: This is related to discussions on EBU R 149 (still being finalised by the EBU).

**Comment by matthewmarks-bbc** [comment]
ST 377-1 says that in the absence of the Signal Standard property, Color Range defaults to max. unsigned int., so is definitely required as it should be 897.

The defaults for Black Ref Level and White Ref Level are correct at 64 and 940 for non-"full range", but as per your advice we should mandate them, as we are not constraining X1 to non-"full range". (That's in the delivery document domain - @andyquested ?)

**Comment by matthewmarks-bbc** [comment]
We are indeed constraining to "narrow range". We will still mandate all three properties, however.

**Comment by matthewmarks-bbc** [comment]
@andyquested re ColorPrimaries: there is a _ITU2020 label registered but no _ITU2100.
