### ISSUE TITLE
AS-11 X8: Are the 35Mbit/s video options required?

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#91]
Are the 35 Mbit/s video encoding options still required? These options have not been seen in any of the example content provided by the broadcasters. Should they be removed from the Spec? If they are to remain in the Spec then we need to see some real examples of content to be sure that this will work OK.

**Comment by thomasheritage** [comment]
Based on recent NABA discussions I believe that these are no-longer required and should be removed. This would only leave two options (both 50 Mbit/s). These are currently named "Option 2a" and "Option 2b" but will be renamed to "Option 1a" and "Option 1b".

@ClydeSm -- please confirm and then the Spec can be updated

**Comment by thomasheritage** [comment]
Confirmed on the NABA call today -- so two modes need to be removed from the Spec

**Comment by ClydeSm** [comment]
Confirmed on the NABA call today only 50 Mbps options will be used

**Comment by matthewmarks-bbc** [comment]
RDD 9 specifies 8 audio channels for 50 Mbit/s modes. The only deviation from conformance with RDD 9 now is allowing up to 16 audio channels, as opposed to exactly 8 for the remaining video options.
