### ISSUE TITLE
AS-11 X8: Confirm that any number of Audio Channels can be included in the file up to a maximum of 16

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#92]

**Comment by thomasheritage** [comment]
I believe that based on recent discussions this is correct. Therefore no change is needed to the Spec on this matter.

@ClydeSm to confirm then I can close this issue.

**Comment by thomasheritage** [comment]
Confirmed on the NABA call today -- so no change needed to the Spec

**Comment by ClydeSm** [comment]
Confirmed on the NABA call today
