### ISSUE TITLE
Using wrong ULs (Key) in dpp example files

### ISSUE THREAD

**Issue by Rico-Z** [AMWA-TV/AS-11_Overview#98]
All the sample files on ftp://ftp.kw.bbc.co.uk/dppdownload/dpp_example_files using the wrong UL (Key) for the following metadata sets: 

1. DM_AS_11_UKDPP_Framework:  
Used UL:               060e2b34.02530101.0d0c0101.01010000
Correct UL:           060e2b34.027f0101.0d0c0101.01010000 

2. DM_AS_11_Segmentation_Framework:
Used UL:               060e2b34.02530101.0d010701.0b020100
Correct UL:           060e2b34.027f0101.0d010701.0b020100 

3. DM_AS_11_Core_Framework:
Used UL:               060e2b34.02530101.0d010701.0b010100
Correct UL:            060e2b34.027f0101.0d010701.0b010100

**Comment by thomasheritage** [comment]
Thanks for reporting the issue.

The ULs you have highlighted are the "Group" / "Class" ULs for the Descriptive Metadata Frameworks. The discrepancy in each case is in Byte 6 of the UL.

These "Groups" are defined in the AS-11 Specifications using [SMPTE Metadata Registers](https://smpte-ra.org/smpte-metadata-registry) XML files. In this format Groups ULs always have Byte 6 set to 0x7F as a "wildcard" value [1]. Ordinarily, when implemented in MXF files, Byte 6 is 0x53 [2] -- this is the case for the MXF files on the FTP site you referenced.

Therefore, the sample files on the FTP site are correct.

I appreciate this situation is not very obvious from the AS-11 Specifications... I've added #99 to address this -- thanks for the feedback.

References, in case you're interested in the details:

1. [SMPTE ST 395:2014](https://doi.org/10.5594/SMPTE.ST395.2014) Section 4.5.4.
2. [SMPTE ST 377-1:2011](https://doi.org/10.5594/SMPTE.ST377-1.2011) Section 9.3 and [SMPTE ST 336:2007](https://doi.org/10.5594/SMPTE.ST336.2007) Table 8

**Comment by Rico-Z** [comment]
Hey,

thank you very much for pointing this out. I was not aware of the "wildcard" mechanism.

Thank´s again and best regards,

Rico
